import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
// import './i18n';

const montserrat = Montserrat({ subsets: ["latin"], weight: ["400", "500", "600", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>{children}</body>
    </html>
  );
}


// 'use client';

// import type { Metadata } from "next";
// import { Montserrat } from "next/font/google";
// import "./globals.css";
// import { appWithTranslation } from 'next-i18next';
// import './i18n'; // Import file i18n đã tạo

// const montserrat = Montserrat({ subsets: ["latin"], weight: ["400", "500", "600", "700"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={montserrat.className}>{children}</body>
//     </html>
//   );
// }

// export default appWithTranslation(RootLayout);